name: docs

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: TopoToolbox/actions/checkout@main
        
      - name: Install Python build dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Build Sphinx documentation
        working-directory: ${{ github.workspace }}
        run: |
          make clean
          make html

      - name: Package artifact
        uses: TopoToolbox/actions/upload-pages-artifact@main
        with:
          path: ${{ github.workspace }}/build/html

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: TopoToolbox/actions/deploy-pages@main
